### ISSUE TITLE
Exception while executing task 59 (paper-220, 1.15.2)

### ISSUE THREAD

**Issue by DiegoDaniel** [Huskehhh/HoneyPopulator#15]
[21:57:50 WARN]: [HoneyPopulator] Plugin HoneyPopulator v1.3.4-SNAPSHOT generated an exception while executing task 59
java.lang.NullPointerException: null
        at pro.husk.honeypopulator.storage.HoneyChunk.serialiseChunkLocation(HoneyChunk.java:65) ~[?:?]
        at pro.husk.honeypopulator.HoneyPopulator.lambda$saveCacheToFile$5(HoneyPopulator.java:320) ~[?:?]
        at pro.husk.honeypopulator.HoneyPopulator$$Lambda$4563/555055996.accept(Unknown Source) ~[?:?]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_51]
        at pro.husk.honeypopulator.HoneyPopulator.saveCacheToFile(HoneyPopulator.java:320) ~[?:?]
        at pro.husk.honeypopulator.HoneyPopulator.lambda$cacheChunk$4(HoneyPopulator.java:295) ~[?:?]
        at pro.husk.honeypopulator.HoneyPopulator$$Lambda$3751/590062107.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-220]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-220]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-220]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_51]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]

**Comment by Huskehhh** [comment]
Can you provide more data? What did you do to make this happen?

**Comment by DiegoDaniel** [comment]
mmhh... i'm just flying around trying to find some bees, because i'm playing with Epic World Generator plugin.

**Comment by Huskehhh** [comment]
That error suggests one of three things, 1: the worldname is null, the x of chunk is null, or the z of chunk is null.

All of which shouldn't occur unless manually editing the data file

Can you provide the data.yml file?

**Comment by DiegoDaniel** [comment]
[data.txt](https://github.com/Huskehhh/HoneyPopulator/files/4549471/data.txt)

**Comment by Huskehhh** [comment]
Unsure about this one, I can't replicate it.. Will look further when I get a chance 👍

**Comment by Huskehhh** [comment]
Couldn't replicate however this should be fixed in the newer builds due to https://github.com/Huskehhh/HoneyPopulator/commit/12438d12954c8856c5d88f1fd20547ba4947f4b3
