### ISSUE TITLE
Error starting the server

### ISSUE THREAD

**Issue by thedourn** [Huskehhh/HoneyPopulator#9]
Hello

I have a problem when starting the server I have this error which runs in a loop

[22:33:28 ERROR]: Could not pass event ChunkLoadEvent to HoneyPopulator v1.3
java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_212]
at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_212]
at pro.husk.honeypopulator.storage.HoneyChunk.getHoneyChunkByChunk(HoneyChunk.java:49) ~[?:?]
at pro.husk.honeypopulator.HoneyPopulator.onChunkLoad(HoneyPopulator.java:129) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor79.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-102]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-102]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-102]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-102]
at net.minecraft.server.v1_15_R1.Chunk.loadCallback(Chunk.java:646) ~[patched_1.15.2.jar:git-Paper-102]
at net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$10(PlayerChunk.java:521) ~[patched_1.15.2.jar:git-Paper-102]
at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[patched_1.15.2.jar:git-Paper-102]
at net.minecraft.server.v1_15_R1.PlayerChunk.lambda$a$11(PlayerChunk.java:519) ~[patched_1.15.2.jar:git-Paper-102]
at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_212]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_212]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_212]
at net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:103) ~[patched_1.15.2.jar:git-Paper-102]
at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:892) ~[patched_1.15.2.jar:git-Paper-102]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-102]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:389) ~[patched_1.15.2.jar:git-Paper-102]
at net.minecraft.server.v1_15_R1.IChunkProvider.getChunkAt(SourceFile:16) ~[patched_1.15.2.jar:git-Paper-102]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getChunkAt(CraftWorld.java:393) ~[patched_1.15.2.jar:git-Paper-102]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getChunkAt(CraftWorld.java:994) ~[patched_1.15.2.jar:git-Paper-102]
at org.bukkit.Location.getChunk(Location.java:123) ~[patched_1.15.2.jar:git-Paper-102]
at me.bigteddy98.bannerboard.e907.b28(Unknown Source) ~[?:?]
at me.bigteddy98.bannerboard.e907.db(Unknown Source) ~[?:?]
at me.bigteddy98.bannerboard.ec9fd.c(Unknown Source) ~[?:?]
at me.bigteddy98.bannerboard.fffa3.run(Unknown Source) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-102]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-102]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-102]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-102]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-102]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-102]

thanks
Thedourn

**Comment by Huskehhh** [comment]
Hey man! Can you provide some more information? 
What storage type are you using?
Is this happening when the server first boots and someone joins shortly after?
Does this occur when 0 players are online 20-30 seconds after boot?

Sorry to be a pain! I suspect I know what is happening I’m just trying to narrow it down :)

**Comment by thedourn** [comment]
Hello
I tested version 33 no longer a problem I used the sql storage and the bug was without player from the start.
